# Generated by Django 3.2.2 on 2022-01-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='paymentMethod',
            field=models.CharField(choices=[('COD', 'COD')], default='COD', max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='drop',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
